/* BACKUP */
USE sucos_vendas;

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\backup\SUCOS_VENDAS02.BAK'

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\backup\SUCOS_VENDAS03.BAK' WITH INIT

BACKUP LOG SUCOS_VENDAS TO DISK = 'C:\backup\SUCOS_VENDAS_LOG01.BAK'

BACKUP LOG SUCOS_VENDAS TO DISK = 'C:\backup\SUCOS_VENDAS_LOG02.BAK' WITH INIT

/*RECUPERAR BACLUP */
ALTER DATABASE SUCOS_VENDAS SET RECOVERY FULL
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\backup\SUCOS_VENDAS03.BAK' WITH INIT

SELECT * FROM [NOTAS FISCAIS]

RESTORE HEADERONLY FROM DISK = 'C:\backup\SUCOS_VENDAS02.BAK'


/* INDICE */
TABELA1 (N AS INT, X AS VARCHAR(10), Y AS BOOLEAN)
CREATE NONCLUSTERED INDEX IDX_NOME ON TABELA1 (X)