/* CRIANDO BANCO */
CREATE DATABASE BANCO01;
USE BANCO01;

CREATE TABLE tbProduto(

	CODIGO VARCHAR(10) NOT NULL PRIMARY KEY,
	DESCRITOR VARCHAR(100) NOT NULL,
	TAMANHO VARCHAR(50),
	EMBALAGEM VARCHAR(50),
	PRECO FLOAT

);

CREATE TABLE tbVendedor(

	MATRICULA VARCHAR(10) NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	BAIRRO VARCHAR(50),
	DATA_ADMISSAO DATE,
	FERIAS BIT

);

CREATE TABLE tbCliente(

	CPF VARCHAR(11) NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO VARCHAR(50),
	CEP VARCHAR(8),
	DATA_NASCIMENTO DATE,
	IDADE INT,
	SEXO VARCHAR(1),
	LIMITE_CREDITO FLOAT,
	VOLUME_COMPRA FLOAT,
	PRIMEIRA_COMPRA BIT

);

CREATE TABLE tbVenda(
	
	NUMERO VARCHAR(5) NOT NULL PRIMARY KEY,
	DATA_VENDA DATE,
	CPF VARCHAR(11) FOREIGN KEY REFERENCES tbCliente(CPF),
	MATRICULA VARCHAR(10) FOREIGN KEY REFERENCES tbVendedor(MATRICULA),
	IMPOSTO FLOAT

);


CREATE TABLE tbItemVenda(
	
	NUMERO VARCHAR(5) FOREIGN KEY REFERENCES tbVenda(NUMERO),
	CODIGO VARCHAR(10) FOREIGN KEY REFERENCES tbProduto(CODIGO),
	QUANTIDADE INT,
	PRECO FLOAT

);