/* FILTRANDO REGISTROS */
USE sucos_vendas;

SELECT TOP 10 * FROM tbProduto;

SELECT * FROM tbProduto
WHERE PRECO_LISTA > 18.5;

SELECT * FROM tbProduto
WHERE PRECO_LISTA < 5;

SELECT * FROM tbCliente
WHERE DATA_NASCIMENTO > '1995-01-01'

SELECT * FROM tbCliente
WHERE YEAR(DATA_NASCIMENTO) = 1995;

SELECT * FROM tbCliente
WHERE MONTH(DATA_NASCIMENTO) = 11;

