/* RELATORIO DE VENDAS */
USE sucos_vendas;

SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO;


SELECT NF.CPF, NF.[DATA], INF.QUANTIDADE FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO;

SELECT NF.CPF, CONVERT(VARCHAR, NF.[DATA], 120) AS DATA_CONVERTIDA, INF.QUANTIDADE FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO;


SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES, INF.QUANTIDADE FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO;

SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7);

SELECT TC.NOME, TC.[VOLUME DE COMPRA] FROM [TABELA DE CLIENTES] TC;

SELECT CQ.ANO_MES, CQ.QUANTIDADE_MES
FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7)) CQ


SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7)) CQ
INNER JOIN [TABELA DE CLIENTES] TC
ON TC.CPF = CQ.CPF;


SELECT AUX1.NOME, AUX1.ANO_MES, AUX1.QUANTIDADE_MES, AUX1.[VOLUME DE COMPRA],
CASE
	WHEN AUX1.QUANTIDADE_MES <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
	WHEN AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA'
	END AS STATUS_VENDA
	FROM
(SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7)) CQ
INNER JOIN [TABELA DE CLIENTES] TC
ON TC.CPF = CQ.CPF) AUX1
ORDER BY AUX1.NOME, AUX1.ANO_MES;

/* ALTERNATIVA B */
SELECT cli.nome,cli.[VOLUME DE COMPRA] as 'volume de compra',substring(convert(varchar,nf.[data],120),1,7) as ano_mes, SUM(INF.[QUANTIDADE]) as total_mes, 
CASE 
	WHEN SUM(INF.[QUANTIDADE]) <= [VOLUME DE COMPRA] THEN 'VENDA VALIDA' 
	WHEN SUM(INF.[QUANTIDADE]) >= [VOLUME DE COMPRA] THEN 'VENDA VALIDA' 
END from [NOTAS FISCAIS] as nf 
inner join [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = inf.NUMERO 
inner join [TABELA DE CLIENTES] as cli 
on cli.CPF = nf.CPF 
GROUP BY NF.CPF,substring(convert(varchar,nf.[data],120),1,7),cli.nome,cli.[VOLUME DE COMPRA]